export const base = "rounded-lg bg-white shadow-lg";
export const title = "font-header font-bold text-3xl text-red-800";
export const divider = "border-1 border-secondary/20 rounded border-red-800";
export const subtitle = "font-header font-semibold text-xl text-neutral-300";
export const leaderboardContainer = "flex flex-col gap-2 mt-2";
export const row = "flex justify-between items-center bg-gray-100 rounded px-3 py-2";
export const rank = "font-bold w-6 text-left";
export const name = "flex-1 ml-2";
export const points = "font-semibold text-right";